### ISSUE TITLE
Testing model on other Datasets

### ISSUE THREAD

**Issue by jahongir7174** [a1600012888/MUTR3D#11]
@a1600012888 
Thanks for sharing your work.
Is it possible to test the model only on cross-view pedestrian tracking datasets such as [WILDRACK](https://www.epfl.ch/labs/cvlab/data/data-wildtrack/) or [MvMHAT](https://github.com/realgump/MvMHAT)?
Thanks in advance.

**Comment by a1600012888** [comment]
Hi, I think you can definitely test it. 
But generally monoculer 3D models is hard to generlize across camera parameters, especiallys for cameras with different focal length.

**Comment by yesokyin** [comment]
Hello, thanks for sharing your work.
Can the code run through nuscenes-mini?
