### ISSUE TITLE
MMDET==2.12.0 is used but incompatible.

### ISSUE THREAD

**Issue by xiao-pengyou** [a1600012888/MUTR3D#13]
I install the mmdetection as readme，but there is an error
There are the versions of openmm
>>> import mmcv
>>> print(mmcv.__version__)
1.3.14
>>> import mmdet
>>> print(mmdet.__version__)
2.12.0
>>> import mmseg
>>> print(mmseg.__version__)
0.29.0
>>> import motmetrics
>>> print(motmetrics.__version__)
1.1.3

And I check out the requarement ,mmdetection3D need 
mmcv-full 1.2.4 1.4.0
mmdet 2.10.0 2.11.0

So I should change the version of mmdet or mmdet3D?

**Comment by yesokyin** [comment]
你好，请问你是怎么解决的呢

**Comment by yesokyin** [comment]
hello, how did you solve it? I met the same problem now.

**Comment by yiqiang-zhang** [comment]
> hello, how did you solve it? I met the same problem now.

I forget what I did，but at that time pytorch1.8.1+cuda10.1 mmcv-full==1.3.14  mmdet==2.12.0 motmetrics==1.1.3 could run， but I have not enough cuda memory(22 GB not enough)，so I give up this method

**Comment by Wu-didi** [comment]
hello, how did you solve it? I met the same problem now.

**Comment by Wu-didi** [comment]
> hello, how did you solve it? I met the same problem now.
Have you solved the problem? I also encountered the same problem.

**Comment by Wu-didi** [comment]
> hello, how did you solve it? I met the same problem now.

Have you solved the problem? I also encountered the same problem

**Comment by yiqiang-zhang** [comment]
> > hello, how did you solve it? I met the same problem now.
> 
> Have you solved the problem? I also encountered the same problem

Sorry, I forget what I have done at that time. Maybe you can try change the version of cudatoolkit.
