### ISSUE TITLE
Can't reproduce the result.

### ISSUE THREAD

**Issue by feifei-Liu** [a1600012888/MUTR3D#14]
Hi,

Thank you very much for your excellent work. I tried to reproduce your results, but found that MOTA was always 0.
<img width="470" alt="fa31ad082611c85dd914569c123e693" src="https://user-images.githubusercontent.com/37265875/198835460-7caaaf7a-a720-4d82-a757-85e329b2beb0.png">

(1) When use your provided json files, it can achieve your results.

(2) When use your provided weights of r101, the MOTA is 0.

(3) When I retrain a model, the MOTA also is 0.

I checked the result json file, and it showed that the result was normal (not NAN), but the track id between the two frames did not correspond. 
<img width="941" alt="c2fa4af2d009a41efd2817d19572cdb" src="https://user-images.githubusercontent.com/37265875/198835766-66b11c49-7f59-4e1a-b574-3ff8d603527f.png">
So I would like to ask how to solve this problem. Thank you very much!

**Comment by a1600012888** [comment]
Hi, 
Can you share the scripts or config file you are using for (2) and (3)? Seems wired, the recall is non-trival but tracking related metrics is zero.

**Comment by a1600012888** [comment]
Hi, I think this mismatch of tracking ids might be caused by this: 
https://github.com/a1600012888/MUTR3D/issues/15
Should already fixed. 
Thanks.

**Comment by Qingfeng800** [comment]
> Hi,
> 
> Thank you very much for your excellent work. I tried to reproduce your results, but found that MOTA was always 0. <img alt="fa31ad082611c85dd914569c123e693" width="470" src="https://user-images.githubusercontent.com/37265875/198835460-7caaaf7a-a720-4d82-a757-85e329b2beb0.png">
> 
> (1) When use your provided json files, it can achieve your results.
> 
> (2) When use your provided weights of r101, the MOTA is 0.
> 
> (3) When I retrain a model, the MOTA also is 0.
> 
> I checked the result json file, and it showed that the result was normal (not NAN), but the track id between the two frames did not correspond. <img alt="c2fa4af2d009a41efd2817d19572cdb" width="941" src="https://user-images.githubusercontent.com/37265875/198835766-66b11c49-7f59-4e1a-b574-3ff8d603527f.png"> So I would like to ask how to solve this problem. Thank you very much!

Hi, I met the same problem with you, how did you solve it later ?

**Comment by ghost** [comment]
> Hi,
> 
> Thank you very much for your excellent work. I tried to reproduce your results, but found that MOTA was always 0. <img alt="fa31ad082611c85dd914569c123e693" width="470" src="https://user-images.githubusercontent.com/37265875/198835460-7caaaf7a-a720-4d82-a757-85e329b2beb0.png">
> 
> (1) When use your provided json files, it can achieve your results.
> 
> (2) When use your provided weights of r101, the MOTA is 0.
> 
> (3) When I retrain a model, the MOTA also is 0.
> 
> I checked the result json file, and it showed that the result was normal (not NAN), but the track id between the two frames did not correspond. <img alt="c2fa4af2d009a41efd2817d19572cdb" width="941" src="https://user-images.githubusercontent.com/37265875/198835766-66b11c49-7f59-4e1a-b574-3ff8d603527f.png"> So I would like to ask how to solve this problem. Thank you very much!

@feifei-Liu 
Hi, I met the same problem with you, how did you solve it later ?
