### ISSUE TITLE
Questions about sample_per_gpu

### ISSUE THREAD

**Issue by yesokyin** [a1600012888/MUTR3D#17]
For training MUTR with ResNet-101. I am using 8 * A100 (40 GB memory per GPU). 
For each gpu, batch_size=1, which means 6 images per GPU.  (at each timestamp, we have images from 6 surronding cameras.)

_Originally posted by @a1600012888 in https://github.com/a1600012888/MUTR3D/issues/3#issuecomment-1176651125_
            How to see in the code: sample is composed of six images

**Comment by a1600012888** [comment]
Hi You can see it in two ways. 
One is the the dataset, like here: 
https://github.com/a1600012888/MUTR3D/blob/main/plugin/track/dataset.py#L305

This forloop put the camera parameters and filepath to `input_dict`. Then the input dict is feed to "Pipeline" to load the images. 

Another place to look is to look at how to generate the dataset meta file.  
Here: 
https://github.com/a1600012888/MUTR3D/blob/main/tools/data_converter/nusc_track.py#L188
