### ISSUE TITLE
Question about visualization

### ISSUE THREAD

**Issue by jianingwangind** [a1600012888/MUTR3D#2]
Great work and thanks for sharing!

Regarding to the result visualization, i have a question: when visualizing with the provided val result json file in front images, all bboxes seem to have a certain offet in z dimension.
![image](https://user-images.githubusercontent.com/40141805/172363815-5b09c1b0-5576-4886-b968-f149096bf795.png)

Do you have any ideas?

**Comment by a1600012888** [comment]
Sorry. A bugs in the dataset._format_box. Will fix soon.

**Comment by a1600012888** [comment]
Fixed. Please download the new results file.

**Comment by jianingwangind** [comment]
thanks a lot. But it seems like that the bboxes are all behind the objects...
![image](https://user-images.githubusercontent.com/40141805/172433100-badcd926-1089-4d3d-8f92-d8c89b2a74fd.png)

**Comment by a1600012888** [comment]
Fixed the box center problem, check at: https://github.com/a1600012888/MUTR3D/blob/main/plugin/track/dataset.py#L572

I updated the new results json file.
