### ISSUE TITLE
AssertionError: assert unachieved_thresholds + duplicate_thresholds + len(thresh_metrics) == self.num_thresholds

### ISSUE THREAD

**Issue by applezy8866** [a1600012888/MUTR3D#20]
I met errors like that when evaluation in topics, and I searched in google found using numpy==1.19.2, but if I change the version of numpy, another bug occurs:
numpy.ndarray size changed, may indicate binary incompatibility. expected 96 from c header, got 80 from pyobject
so which version of numpy should I use?

**Comment by a1600012888** [comment]
Hi, 
What is the version of your motmetrics? 
Current evalutation code need motmetrics==1.1.3
