### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by jianingwangind** [a1600012888/MUTR3D#3]
Hi, another question, maybe missing files in /plugin/track/models/tracker.py?
![image](https://user-images.githubusercontent.com/40141805/172563125-2658fede-3ee4-40b0-97de-600f5236f8ff.png)

**Comment by a1600012888** [comment]
Thanks for pointing this out. 

Seems I forget to add grid mask to the plugin directory. 

Just added.  https://github.com/a1600012888/MUTR3D/blob/main/plugin/track/models/grid_mask.py

**Comment by jianingwangind** [comment]
thanks

**Comment by jianingwangind** [comment]
![image](https://user-images.githubusercontent.com/40141805/172817170-830d537c-7704-4064-9156-ba706520c9f1.png)
can you train maybe missing files again?

**Comment by jianingwangind** [comment]
Hi, i keep encountering the import error, do you have any ideas?
![image](https://user-images.githubusercontent.com/40141805/172827641-82a3667f-8528-4f83-833c-741c169191c2.png)

**Comment by a1600012888** [comment]
Hi, which file does the error comes from? seems in mmdet/modes/__init__.py?

**Comment by jianingwangind** [comment]
Thanks, i did that as well. Also there are bugs in init_weight function of MVXTwoStage detector
![image](https://user-images.githubusercontent.com/40141805/172976338-72f55bcd-2455-4bbc-a078-86562b7f4344.png)

**Comment by a1600012888** [comment]
The model is trained around half a year ago... I will try to find the log.  For the enviroment: 
running `python3 mmdet3d/utils/collect_env.py` gives:

![image](https://user-images.githubusercontent.com/26039822/173117523-8f0423a7-889d-4eeb-9360-2bfce571254e.png)

**Comment by a1600012888** [comment]
Hi, I checked the code. 
Seems a little difference on the file `mmdet3d/models/detectors/mvx_two_stage.py`.  I uploaded with my version. 
I sometimes made several small modifications to the mmdetection3d code, but forget to update, sorry about this. 

Or, if you want the whole modified mmdet3d code, I probably can upload that.

**Comment by jianingwangind** [comment]
That would be great! Please upload that and i really appreciate :) thanks a lot @a1600012888

**Comment by jianingwangind** [comment]
@a1600012888 Is there a typo in config file?

![image](https://user-images.githubusercontent.com/40141805/173330436-48372901-632e-4cde-b835-87c000c9e434.png)
 why is the radar related pkl file used for training and test?

**Comment by a1600012888** [comment]
> That would be great! Please upload that and i really appreciate :) thanks a lot @a1600012888

I uploaded mmdet3d_full.

**Comment by a1600012888** [comment]
> @a1600012888 Is there a typo in config file?
> 
> ![image](https://user-images.githubusercontent.com/40141805/173330436-48372901-632e-4cde-b835-87c000c9e434.png) why is the radar related pkl file used for training and test?

Radar is not used in the training. I tried to do some radar experiments in the early stage of this project, but didn't continue. 

In the provided code, there are several pieces of code that you can use if you want to use radars.

**Comment by jianingwangind** [comment]
Thanks a lot. May i ask how many gpu machines are you using and the batch size per gpu?

**Comment by jianingwangind** [comment]
Thanks a lot :)

**Comment by jianingwangind** [comment]
and may i ask how long in total did you train the model?

**Comment by jianingwangind** [comment]
Thanks. Have you done any experiments regarding to the detection performance difference i.e. mAP, between DETR3D and MUTR3D?

**Comment by a1600012888** [comment]
I feel they should be similar, because the feature extractor is the same, and the head is similar. But I didn't evalute the detection performance of the tracker.

**Comment by jianingwangind** [comment]
Thanks, I agree. 
I can train the model now but the training process keeps hanging at a certain iter, have you ever encountered this problem? Seems like a multi-gpu training problem.
<img width="810" alt="5a01ced6312038431077b6ada48e861" src="https://user-images.githubusercontent.com/40141805/178180211-9c02a6ba-fdb5-4b99-af59-510f95608bfc.png">

**Comment by XuanjieXiao** [comment]
sorry to bother you!
I had some issues which need your help!
![2022-07-13 17-00-08 的屏幕截图](https://user-images.githubusercontent.com/44575663/178695087-5e71f6f1-b2b5-4b71-8f98-2be2cdf882fe.png)

ImportError: /home/nvidia/MUTR3D/mmdetection3d/mmdet3d/ops/iou_loss/iou_loss_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefIlEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEE

**Comment by XuanjieXiao** [comment]
**sorry to bother you again!
I don't know how to use this command:**
`CUDA_VISIBLE_DEVICES=0 bash tools/dist_train_tracker.sh plugin/track/configs/resnet101_fpn_3frame.py 1 --work-dir=Test01/Test01`

**because my GPU Memory is only 12GB and I only got 1 GPU.**

1. therefore, I am wondering could you please show me which parameters in <resnet101_fpn_3frame.py>  to change to fit my envs?
2. and I dont know how to use <tools/nusc_visualizer.py>?

Thanks !!  <~!0.0!~>

**Comment by KeyuLi** [comment]
> **sorry to bother you! I had some issues and need your help!** ![2022-07-13 17-00-08 的屏幕截图](https://user-images.githubusercontent.com/44575663/178695087-5e71f6f1-b2b5-4b71-8f98-2be2cdf882fe.png)
> 
> ImportError: /home/nvidia/MUTR3D/mmdetection3d/mmdet3d/ops/iou_loss/iou_loss_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefIlEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEE
> 
> **my pytorch version is '1.9.0+cu111' python3.7 torchversion '0.10.0+cu111' may I ask what kind of environments do you use?**

I have the same issues, do you solve it?

**Comment by XuanjieXiao** [comment]
> 

yes, It's the version problem!
see the auther's envs version!
https://github.com/a1600012888/MUTR3D/issues/3#issuecomment-1152571147

**Comment by KeyuLi** [comment]
> > 
> 
> yes, It's the version problem! see the auther's envs version! [#3 (comment)](https://github.com/a1600012888/MUTR3D/issues/3#issuecomment-1152571147)

thx,  I found this problem is caused by the used of "giou_loss", I think users can replace it by normal "iou_loss"  (maybe a little different) if they don't want to upgrade the version of mmdet3d.

**Comment by XuanjieXiao** [comment]
> > > 
> > 
> > 
> > yes, It's the version problem! see the auther's envs version! [#3 (comment)](https://github.com/a1600012888/MUTR3D/issues/3#issuecomment-1152571147)
> 
> thx, I found this problem is caused by the used of "giou_loss", I think users can replace it by normal "iou_loss" (maybe a little different) if they don't want to upgrade the version of mmdet3d.

giou是三维的，你去看看吧，反正我发现是版本问题，我换了版本就好了

**Comment by KeyuLi** [comment]
iou也是3d的呀。。版本问题就是因为在giou.so里面的编译导致的啊。换了版本也可以，但是如果想用其他版本的话可以把giou换成iouloss就好，就不会报错了。

FDU_XuanjieXiao ***@***.***> 于2022年7月18日周一 11:45写道：

**Comment by yesokyin** [comment]
> **sorry to bother you again! I don't know how to use this command:** `CUDA_VISIBLE_DEVICES=0 bash tools/dist_train_tracker.sh plugin/track/configs/resnet101_fpn_3frame.py 1 --work-dir=Test01/Test01`
> 
> **because my GPU Memory is only 12GB and I only got 1 GPU.**
> 
> 1. therefore, I am wondering could you please show me which parameters in <resnet101_fpn_3frame.py>  to change to fit my envs?
> 2. and I dont know how to use <tools/nusc_visualizer.py>?
> 
> Thanks !! <~!0.0!~>

Hello, I also have the same problem, how did you solve it
