### ISSUE TITLE
Error occur when training

### ISSUE THREAD

**Issue by shawrby** [a1600012888/MUTR3D#5]
Hi there,

I have read your excellent paper.

But when I try to train the model, I get the following error:

![image](https://user-images.githubusercontent.com/54407464/174812068-1b9a04f0-bd5d-4d63-9188-4e377499b004.png)
![image](https://user-images.githubusercontent.com/54407464/174813673-5a90d853-e9c5-462c-8253-ec309eda36ff.png)

Errors are occurring in 'Normalize3D' and 'Pad3D' in the config file.

What am I missing?

**Comment by a1600012888** [comment]
Yes, I missed some file. 

I uploaded `mmdet3d_full`.  You can replace the `mmdet3d` with the `mmdet3d_full`
