### ISSUE TITLE
error occurred and there's no results update after 40 epoch as shown in this command after eval

### ISSUE THREAD

**Issue by XuanjieXiao** [a1600012888/MUTR3D#7]
`2022-07-21 09:04:35,386 - mmdet - INFO - Epoch(val) [44][321]	pts_bbox_NuScenes/amota: 0.0000, pts_bbox_NuScenes/amotp: 2.0000, pts_bbox_NuScenes/recall: 0.0000, pts_bbox_NuScenes/motar: 0.0000, pts_bbox_NuScenes/gt: 611.5000, pts_bbox_NuScenes/mota: 0.0000, pts_bbox_NuScenes/motp: 2.0000, pts_bbox_NuScenes/mt: 0.0000, pts_bbox_NuScenes/ml: 203.0000, pts_bbox_NuScenes/faf: 500.0000, pts_bbox_NuScenes/tp: 0.0000, pts_bbox_NuScenes/fp: 0.0000, pts_bbox_NuScenes/fn: 3669.0000, pts_bbox_NuScenes/ids: 0.0000, pts_bbox_NuScenes/frag: 0.0000, pts_bbox_NuScenes/tid: 20.0000, pts_bbox_NuScenes/lgd: 20.0000`

**sorry to bother you again !
I've trained this for a long time! Suddenly, I saw this results in the training log. So I deploy the eval command like you told us to do.
But I got this results and this error. I've looked all over the Internet , but I cannot find a solution.**
![image](https://user-images.githubusercontent.com/44575663/181173980-c2f976f3-70cc-4cd9-91ed-5519533133f7.png)

AMOTA   0.000
AMOTP   2.000
RECALL  0.000
MOTAR   0.000
GT      14556
MOTA    0.000
MOTP    2.000
MT      0
ML      6470
FAF     500.0
TP      0
FP      0
FN      101897
IDS     0
FRAG    0
TID     20.00
LGD     20.00

what's more, my command is listed below.
`python tools/test.py Test01/Full_Train/resnet101_fpn_3frame_full.py Test01/Test02/epoch_45.pth --eval bbox`

But when I use the pretrained model like "mutr3d_res101.pth", which is downloaded from your GitHub, the program can run correctly.
looking forward to your reply ! thks

**Comment by XuanjieXiao** [comment]
> Hi, I suspect your model went to nan. Can you generate the results json file, `python3 tools/test.py plugin/track/configs/resnet101_fpn_3frame.py <model-path> --format-only --eval-options jsonfile_prefix=<dir-name-for-saving-json-results>` I believe the model will only output nan for any input.

yes! I can generate the results json file.
[results_nusc.zip](https://github.com/a1600012888/MUTR3D/files/9204523/results_nusc.zip)

**Comment by ghost** [comment]
> `2022-07-21 09:04:35,386 - mmdet - INFO - Epoch(val) [44][321] pts_bbox_NuScenes/amota: 0.0000, pts_bbox_NuScenes/amotp: 2.0000, pts_bbox_NuScenes/recall: 0.0000, pts_bbox_NuScenes/motar: 0.0000, pts_bbox_NuScenes/gt: 611.5000, pts_bbox_NuScenes/mota: 0.0000, pts_bbox_NuScenes/motp: 2.0000, pts_bbox_NuScenes/mt: 0.0000, pts_bbox_NuScenes/ml: 203.0000, pts_bbox_NuScenes/faf: 500.0000, pts_bbox_NuScenes/tp: 0.0000, pts_bbox_NuScenes/fp: 0.0000, pts_bbox_NuScenes/fn: 3669.0000, pts_bbox_NuScenes/ids: 0.0000, pts_bbox_NuScenes/frag: 0.0000, pts_bbox_NuScenes/tid: 20.0000, pts_bbox_NuScenes/lgd: 20.0000`
> 
> **sorry to bother you again ! I've trained this for a long time! Suddenly, I saw this results in the training log. So I deploy the eval command like you told us to do. But I got this results and this error. I've looked all over the Internet , but I cannot find a solution.** ![image](https://user-images.githubusercontent.com/44575663/181173980-c2f976f3-70cc-4cd9-91ed-5519533133f7.png)
> 
> AMOTA 0.000 AMOTP 2.000 RECALL 0.000 MOTAR 0.000 GT 14556 MOTA 0.000 MOTP 2.000 MT 0 ML 6470 FAF 500.0 TP 0 FP 0 FN 101897 IDS 0 FRAG 0 TID 20.00 LGD 20.00
> 
> what's more, my command is listed below. `python tools/test.py Test01/Full_Train/resnet101_fpn_3frame_full.py Test01/Test02/epoch_45.pth --eval bbox`
> 
> But when I use the pretrained model like "mutr3d_res101.pth", which is downloaded from your GitHub, the program can run correctly. looking forward to your reply ! thks

Hi, I meet the same problem with you, how do you solve it later ?

**Comment by a1600012888** [comment]
Hi Qingfeng. 

Have you tested if your model output nan?
