### ISSUE TITLE
how to use checkpoints and log to continue training?

### ISSUE THREAD

**Issue by XuanjieXiao** [a1600012888/MUTR3D#9]
what's more, I'm curious how to continue training if my program was stopped by accidents! so how to use checkpoints to continue training?
thks! looking forward to your reply !

**Comment by a1600012888** [comment]
Hi, Xuanjie 

For resume the training, yes you can do that. 
See here: https://github.com/a1600012888/MUTR3D/blob/main/tools/train_tracker.py#L27

If you just want to load the one of the checkpoint and start a new training schdule, you can change the `load_from` in config file https://github.com/a1600012888/MUTR3D/blob/main/plugin/track/configs/resnet50_fpn_5frame.py#L270

**Comment by XuanjieXiao** [comment]
> Hi, Xuanjie
> 
> For resume the training, yes you can do that. See here: https://github.com/a1600012888/MUTR3D/blob/main/tools/train_tracker.py#L27
> 
> If you just want to load the one of the checkpoint and start a new training schdule, you can change the `load_from` in config file https://github.com/a1600012888/MUTR3D/blob/main/plugin/track/configs/resnet50_fpn_5frame.py#L270

thks！！！
